---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_none # Chef outputs an ugly SSL warning otherwise

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
    - recipe[apt] # get updated package list for java
    - recipe[java]
    - recipe[cassandra-opscenter::default]
    - role[cassandra-test-cluster]
  attributes:
    ec2:
      public_hostname: localtest.me

- name: non_first_role
  run_list:
    - recipe[apt]
    - recipe[java]
    - recipe[cassandra-opscenter::default]
    - role[another-role]
    - role[cassandra-test-cluster]
  attributes:
    ec2:
      public_hostname: localtest.me
